---
volumes:
  shares:
services:
  # SERVER
  server:
    image: ghcr.io/yanhao98/unicloud:latest
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "2222:22"
      - "5001:80"
    hostname: unicloud.server.local
    environment:
      - TZ=Asia/Shanghai
      - USER=root
      - USER_UID=0
      # - USER_GIDS=33,14
      - SERVER_UI_USERNAME=admin
      - SERVER_UI_PASSWORD=
      - SERVER_DEBUG=True
      - ROLE=SERVER
    networks:
      unison:
        aliases:
          - unicloud_server
    volumes:
      - type: bind
        source: ./server
        target: /data
      - type: volume
        source: shares
        target: /shares
      # ##########################################################
      # - type: bind
      #   source: ../../start/start.py
      #   target: /start/start.py
      # - type: bind
      #   source: ../../start/shell_cmd.py
      #   target: /start/shell_cmd.py
      # - type: bind
      #   source: ../../start/templates/unicloud.tpl.ini
      #   target: /start/templates/unicloud.tpl.ini
      # - type: bind
      #   source: ../../app/db_conn.py
      #   target: /usr/local/unicloud/db_conn.py
  # CLIENT
  client:
    image: ghcr.io/yanhao98/unicloud:latest
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - TZ=Asia/Shanghai
      - CLIENT_HOSTNAME=testing-client1
      - ROLE=CLIENT
      - USER=root
      - USER_UID=0
      - SERVER_HOSTNAME=unicloud_server
      - SERVER_PORT=22
      - SERVER_SHARE=share1
      - UNISON_PARAMS=group = true|owner = true|times = true
      - API_PROTOCOL=http
      - API_PORT=80
      - SYNC_INTERVAL=5
    restart: on-failure
    volumes:
      - type: bind
        source: ./client
        target: /data
      - type: bind
        source: ./client/share
        target: /data/share
      # ##########################################################
      # - type: bind
      #   source: ../../start/start.py
      #   target: /start/start.py
      # - type: bind
      #   source: ../../start/shell_cmd.py
      #   target: /start/shell_cmd.py
      # - type: bind
      #   source: ../../conf/sshd/client_root_ssh_config
      #   target: /root/.ssh/config
      # - type: bind
      #   source: ../../app_client/main.py
      #   target: /usr/local/unicloud_client/main.py
    networks:
      unison:

networks:
  unison:
    # driver: bridge
    # ipam:
    #   driver: default
