on:
  push:
    branches:
      - run-as-root
    paths-ignore:
      - 'examples/**'
      - 'docs/**'
env:
  TZ: Asia/Shanghai

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: yanhao98/composite-actions/docker-build-push@main
        id: docker-build-push
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          load: false
          meta_images: |
            ghcr.io/${{ github.repository }}
          meta_tags: | # https://github.com/docker/metadata-action
            type=raw,value=latest,enable=true
